name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tuist
        run: |
            bash <(curl -Ls https://install.tuist.io)
            tuist bundle
            tuist generate
            tuist test
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
